CREATE TABLE IF NOT EXISTS `ops_telco_rfos` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `ticket_number` varchar(50) NOT NULL,
  `problem_id` int NULL,
  `company_id` int NULL,
  `device_id` int NULL,
  `rfo_date` date NOT NULL,
  `start_time` varchar(80) NOT NULL,
  `end_time` varchar(80) NOT NULL,
  `cause` text NOT NULL,
  `impact` text NOT NULL,
  `solution` text NOT NULL,
  `status` text NOT NULL,
  `notes` text NULL,
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT NOW(),
  `updated_at` timestamp NOT NULL DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `ops_telco_rfos_ticket_unique` (`ticket_number`),
  INDEX `ops_telco_rfos_problem_idx` (`problem_id`),
  INDEX `ops_telco_rfos_company_idx` (`company_id`),
  INDEX `ops_telco_rfos_date_idx` (`rfo_date`),
  CONSTRAINT `ops_telco_rfos_problem_fk` FOREIGN KEY (`problem_id`) REFERENCES `kpi_report_problems` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ops_telco_rfos_company_fk` FOREIGN KEY (`company_id`) REFERENCES `kpi_companies` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ops_telco_rfos_device_fk` FOREIGN KEY (`device_id`) REFERENCES `kpi_devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `ops_telco_rfos_user_fk` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT
);
